"use server";
import axios from "axios";
import { env } from "@/lib/env";
import { isbot } from "isbot";
import { headers } from "next/headers";

interface EmailData {
  name: string;
  email: string;
  subject: string;
  message: string;
}

export default async function sendEmail({ name, email, subject, message }: EmailData) {
  const headersList = headers();
  const userAgent = headersList.get("user-agent");

  console.log(userAgent);

  if (isbot(userAgent)) {
    return;
  }

  const emailTemplate = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Form Submission</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            color: #333;
        }
        .email-container {
            max-width: 600px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        h2 {
            color: #444;
            font-size: 22px;
            margin-top: 0;
        }
        p {
            font-size: 16px;
            line-height: 1.5;
        }
        .details {
            background-color: #f9f9f9;
            padding: 10px;
            border-radius: 5px;
            margin-top: 20px;
        }
        .details p {
            margin: 0;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            color: #888;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <h2>New Contact Form Submission</h2>
        <p>Hello Coen,</p>
        <p>You have received a new message from the contact form on your website.</p>
        <div class="details">
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Subject:</strong> ${subject}</p>
            <p><strong>Message:</strong></p>
            <p>${message}</p>
        </div>
        <p>Best regards,<br>Your Website Team</p>
        <div class="footer">
            <p>This email was automatically generated by your website. Please do not reply.</p>
        </div>
    </div>
</body>
</html>
`;

  try {
    const res = await axios.post(
      "https://api.smtp2go.com/v3/email/send",
      { to: ["info@coenmeteenc.com"], subject: `new form submission <${subject}>`, html_body: emailTemplate, sender: "no-reply@coenmeteenc.com" },
      {
        headers: { accept: "application/json", "Content-Type": "application/json", "X-Smtp2go-Api-Key": env.SMTP2GO_API_KEY },
      }
    );
    return res.data;
  } catch (error: any) {
    console.log(error.response);
  }
}
